#!/bin/bash

echo "🚀 DBSCAN Fraud Detection - Guía de Deployment"
echo "=============================================="
echo ""
echo "📋 PASO 1: Crear Repositorio en GitHub"
echo "--------------------------------------"
echo "1. Ve a: https://github.com/new"
echo "2. Nombre del repositorio: api-dbscan (o dbscan-fraud-detection)"
echo "3. Descripción: Sistema de detección de fraude bancario con DBSCAN"
echo "4. Público o Privado (tu elección)"
echo "5. NO marques 'Add README', 'Add .gitignore' ni 'Choose a license'"
echo "6. Click en 'Create repository'"
echo ""
echo "📋 PASO 2: Copiar la URL del repositorio"
echo "--------------------------------------"
echo "Copia la URL que aparece, ejemplo:"
echo "https://github.com/TU-USUARIO/api-dbscan.git"
echo ""
read -p "Pega aquí la URL de tu repositorio: " REPO_URL

if [ -z "$REPO_URL" ]; then
    echo "❌ Error: No se proporcionó URL"
    exit 1
fi

echo ""
echo "📋 PASO 3: Conectando con GitHub..."
echo "--------------------------------------"
git remote add origin "$REPO_URL"
git remote -v

echo ""
echo "📋 PASO 4: Subiendo código a GitHub..."
echo "--------------------------------------"
git push -u origin main

echo ""
echo "✅ ¡Código subido exitosamente a GitHub!"
echo ""
echo "=============================================="
echo "📋 PASO 5: Deployment en Render"
echo "=============================================="
echo ""
echo "1. Ve a: https://dashboard.render.com/"
echo "2. Click en 'New +' → 'Web Service'"
echo "3. Conecta tu cuenta de GitHub"
echo "4. Selecciona el repositorio: $(basename $REPO_URL .git)"
echo ""
echo "5. Configuración:"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Name:          dbscan-fraud-detection"
echo "   Region:        Oregon (US West)"
echo "   Branch:        main"
echo "   Runtime:       Python 3"
echo "   Build Command: pip install -r requirements.txt"
echo "   Start Command: gunicorn app_static:app"
echo "   Instance Type: Free"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "6. Click en 'Create Web Service'"
echo "7. Espera 2-3 minutos mientras se despliega"
echo "8. ¡Tu app estará en vivo!"
echo ""
echo "=============================================="
echo "📱 URLs Importantes"
echo "=============================================="
echo ""
echo "🔗 Tu repositorio: $REPO_URL"
echo "🔗 Render Dashboard: https://dashboard.render.com/"
echo "🔗 Tu app estará en: https://dbscan-fraud-detection.onrender.com"
echo "   (o el nombre que elijas)"
echo ""
echo "=============================================="
echo "💡 Próximos Pasos"
echo "=============================================="
echo ""
echo "1. ✅ Código subido a GitHub"
echo "2. ⏳ Siguiente: Ir a Render y hacer el deployment"
echo "3. 📝 Actualizar README.md con la URL de tu app en vivo"
echo "4. 🎉 ¡Compartir tu proyecto!"
echo ""
echo "¿Necesitas ayuda? Revisa: README_DEPLOYMENT.md"
echo ""
